spring:
  # mvc:
  #   pathmatch:
  #     matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: jdbc:postgresql://postgresql-chdprojets.alwaysdata.net/chdprojets_ecommerce
    username: chdprojets_commerce
    password: ortide66720
    # driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
